const WORLD={w:20,h:72};const MOVE_SPEED=280;const CHARACTER_SCALE=1.75;
const ZONES=[{name:'河畔商店街',z:-24},{name:'花守中央廣場',z:0},{name:'南風村口',z:24}];
const npcs=[
 {x:-2.2,z:3.8,name:'莉亞',face:0,lines:['旅行者，你好！這裡是花守村，我是照顧花圃的莉亞。','沿著中央石板路一直走，就能抵達河畔商店街。','三條街道都和廣場相連，所以不用擔心迷路。','等星鈴花盛開時，我請你喝村裡最好喝的蜂蜜茶！']},
 {x:3,z:25,name:'米洛',face:1,lines:['你就是剛來的旅行者吧？我是木匠米洛。','南邊這條寬路通往村口，兩旁都是新修好的木屋。','沿著淺色石板走，便不會踩進居民的花圃。','有空再來，我會替你做一雙更適合旅行的靴子。']},
 {x:3,z:-17,name:'莎婆婆',face:2,lines:['呵呵，年輕人，你終於走到河畔來了。','過橋後是麵包坊，清晨總能聞到蜂蜜麵包的香味。','溪水不能直接走過去，要從中央石橋通行。','記住道路不只是方向，也是村民一起生活的痕跡。']},
 {x:3,z:-30,name:'艾妲',face:3,lines:['歡迎來到河畔麵包坊！我是店主艾妲。','今天烤的是蜂蜜核桃麵包，香味連橋那頭都聞得到。','莉亞說你正在認識村子，所以這一個送給你。','下次帶朋友一起來，我會替你們留靠窗的位置！']},
 {x:3,z:21,name:'凱恩',face:4,lines:['站住……啊，是新來的旅行者。我是巡守凱恩。','村裡很和平，但夜裡過橋還是要留意濕滑的石階。','若看到圍籬損壞，請告訴我或木匠米洛。','放心探索吧，我會守著通往村外的道路。']},
 {x:-3,z:-1.5,name:'菲菲',face:5,lines:['你也是來看廣場噴泉的嗎？我是菲菲！','我每天都數水花，可是每次數到二十就忘記了。','莎婆婆說，忘記的願望會變成河邊的小花。','所以我決定再許一個願望：希望你明天也會來！']}
];
const BUILDINGS=['guild','magic','alchemy','smithy','tavern','bakery','flower','chapel','home','clocktower','market'];
let engine,scene,camera,player,shadowGenerator,activeNpc=null,line=0,talking=false,vector={x:0,y:0},origin=null,direction='down',zoneIndex=-1,walkClock=0;
function material(name,color){const m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=BABYLON.Color3.Black();return m;}
function pixelTexture(url){const t=new BABYLON.Texture(url,scene,false,true,BABYLON.Texture.NEAREST_SAMPLINGMODE);t.hasAlpha=true;return t;}
function spriteMaterial(name,url){const m=new BABYLON.StandardMaterial(name,scene);m.diffuseTexture=pixelTexture(url);m.opacityTexture=m.diffuseTexture;m.useAlphaFromDiffuseTexture=true;m.backFaceCulling=false;m.specularColor=BABYLON.Color3.Black();return m;}
function box(name,x,y,z,w,h,d,mat,collision=false){const mesh=BABYLON.MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);mesh.position.set(x,y,z);mesh.material=mat;mesh.checkCollisions=collision;mesh.receiveShadows=true;return mesh;}
function createGround(){
 const grass=[material('south','#71984d'),material('square','#668f48'),material('riverbank','#527f4b')];
 ZONES.forEach((zone,i)=>{const g=BABYLON.MeshBuilder.CreateGround(`ground-${i}`,{width:20,height:24,subdivisions:2},scene);g.position.z=zone.z;g.material=grass[2-i];g.receiveShadows=true;});
 const road=material('pixel-cobbles','#b8aa91');road.diffuseTexture=new BABYLON.DynamicTexture('roadPixels',{width:128,height:128},scene,false,BABYLON.Texture.NEAREST_SAMPLINGMODE);const ctx=road.diffuseTexture.getContext();ctx.fillStyle='#b8aa91';ctx.fillRect(0,0,128,128);for(let y=4;y<128;y+=20)for(let x=(y/20%2)*14;x<128;x+=28){ctx.fillStyle='#897f72';ctx.fillRect(x,y,23,13);ctx.fillStyle='#d8cdb7';ctx.fillRect(x+2,y+2,18,2);}road.diffuseTexture.update();road.diffuseTexture.uScale=2;road.diffuseTexture.vScale=18;
 box('main-road',0,.025,0,3.4,.05,72,road);box('south-crossroad',0,.03,24,15,.06,3,road);box('square-road',0,.035,0,15,.07,6,road);
 const water=material('river','#2f839b');water.alpha=.88;box('river',0,.01,-12,20,.08,4,water);const bridge=material('bridge','#9a683d');box('bridge',0,.14,-12,3.5,.25,4.4,bridge);const riverWall=material('river-wall','#245f72');for(const x of [-5.9,5.9]){const barrier=box(`river-barrier-${x}`,x,.7,-12,8.2,1.4,3.6,riverWall,true);barrier.isVisible=false;}
 for(let z=-33;z<35;z+=4){box(`edge-l-${z}`,-10,.65,z,.2,1.3,4,grass[0],true).isVisible=false;box(`edge-r-${z}`,10,.65,z,.2,1.3,4,grass[0],true).isVisible=false;}
}
function createBuilding(key,x,z,width=5,height=4.6,flip=false){const plane=BABYLON.MeshBuilder.CreatePlane(`building-${key}`,{width,height},scene);plane.position.set(x,height/2,z);plane.billboardMode=BABYLON.Mesh.BILLBOARDMODE_Y;plane.material=spriteMaterial(`mat-${key}-${x}-${z}`,`assets/buildings/${key}.png`);plane.material.diffuseTexture.uScale=flip?-1:1;if(flip)plane.material.diffuseTexture.uOffset=1;const blocker=box(`wall-${key}`,x,.8,z,width*.65,1.6,.65,material(`wallmat-${key}-${x}-${z}`,'#223329'),true);blocker.isVisible=false;shadowGenerator.addShadowCaster(plane);return plane;}
function createTown(){let n=0;[-31,-26,-21,-16,-7,-2,3,8,15,20,25,30].forEach((z,row)=>{for(const x of [-6.4,6.4])createBuilding(BUILDINGS[n++%BUILDINGS.length],x,z,4.8+(row%3)*.35,4.2+(row%4)*.25,x>0);});createBuilding('clocktower',-6.6,33,3.6,6.2);createBuilding('market',6.3,33,5.4,4.1,true);}
function createBillboard(name,url,x,z,width,height){const p=BABYLON.MeshBuilder.CreatePlane(name,{width,height},scene);p.position.set(x,height/2,z);p.billboardMode=BABYLON.Mesh.BILLBOARDMODE_Y;p.material=spriteMaterial(`${name}-mat`,url);return p;}
function setSpriteFrame(mesh,column,row,columns,rows){const t=mesh.material.diffuseTexture;t.uScale=1/columns;t.vScale=1/rows;t.uOffset=column/columns;t.vOffset=row/rows;}
function loadAssets(){player=createBillboard('player','assets/hero-walk.png',0,28,1.3,1.8);player.ellipsoid=new BABYLON.Vector3(.32,.8,.22);player.ellipsoidOffset=new BABYLON.Vector3(0,.85,0);player.checkCollisions=true;setSpriteFrame(player,1,0,3,4);shadowGenerator.addShadowCaster(player);npcs.forEach((n,i)=>{n.sprite=createBillboard(`npc-${i}`,`assets/npcs/npc-idle-${i}.png`,n.x,n.z,1.25,1.75);setSpriteFrame(n.sprite,1,0,3,1);shadowGenerator.addShadowCaster(n.sprite);});}
function createEnvironmentEffects(){const ps=new BABYLON.ParticleSystem('light-motes',80,scene);ps.particleTexture=new BABYLON.DynamicTexture('mote',{width:16,height:16},scene,false,BABYLON.Texture.NEAREST_SAMPLINGMODE);const pc=ps.particleTexture.getContext();pc.fillStyle='white';pc.beginPath();pc.arc(8,8,5,0,Math.PI*2);pc.fill();ps.particleTexture.update();ps.emitter=new BABYLON.Vector3(0,4,0);ps.minEmitBox=new BABYLON.Vector3(-9,0,-35);ps.maxEmitBox=new BABYLON.Vector3(9,4,35);ps.color1=new BABYLON.Color4(1,.86,.48,.5);ps.color2=new BABYLON.Color4(.8,1,.7,.25);ps.minSize=.03;ps.maxSize=.12;ps.minLifeTime=4;ps.maxLifeTime=8;ps.emitRate=8;ps.gravity=new BABYLON.Vector3(0,.02,0);ps.start();}
function setupPostProcess(){const pipeline=new BABYLON.DefaultRenderingPipeline('cinematic',true,scene,[camera]);pipeline.samples=1;pipeline.fxaaEnabled=true;pipeline.bloomEnabled=true;pipeline.bloomThreshold=.86;pipeline.bloomWeight=.12;pipeline.depthOfFieldEnabled=true;pipeline.depthOfFieldBlurLevel=BABYLON.DepthOfFieldEffectBlurLevel.Low;pipeline.depthOfField.focusDistance=2400;pipeline.depthOfField.fStop=5.6;pipeline.imageProcessingEnabled=true;pipeline.imageProcessing.contrast=1.08;pipeline.imageProcessing.exposure=.96;pipeline.imageProcessing.vignetteEnabled=true;pipeline.imageProcessing.vignetteWeight=1.25;pipeline.imageProcessing.vignetteColor=new BABYLON.Color4(.04,.08,.07,1);}
function createScene(){scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.08,.13,.18,1);scene.collisionsEnabled=true;camera=new BABYLON.FreeCamera('camera',new BABYLON.Vector3(0,9,36),scene);camera.mode=BABYLON.Camera.ORTHOGRAPHIC_CAMERA;camera.setTarget(new BABYLON.Vector3(0,0,28));camera.rotation.x=Math.PI/5.5;camera.inputs.clear();resizeCamera();new BABYLON.HemisphericLight('sky',new BABYLON.Vector3(0,1,0),scene).intensity=1.05;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.45,-1,.5),scene);sun.position.set(8,14,-8);sun.intensity=1.25;shadowGenerator=new BABYLON.ShadowGenerator(1024,sun);shadowGenerator.useBlurExponentialShadowMap=true;shadowGenerator.blurKernel=12;createGround();createTown();loadAssets();createEnvironmentEffects();setupPostProcess();scene.onBeforeRenderObservable.add(update);return scene;}
function resizeCamera(){if(!camera)return;const aspect=engine.getRenderWidth()/engine.getRenderHeight();const view=13;camera.orthoTop=view;camera.orthoBottom=-view;camera.orthoLeft=-view*aspect;camera.orthoRight=view*aspect;}
function animatePlayer(moving,dt){if(!moving){setSpriteFrame(player,1,{down:0,left:1,right:2,up:3}[direction],3,4);return;}walkClock+=dt;setSpriteFrame(player,Math.floor(walkClock*8)%3,{down:0,left:1,right:2,up:3}[direction],3,4);}
function move(dx,dy){vector={x:dx,y:dy};}
function update(){if(!player||talking)return;let x=vector.x,y=vector.y;if(keys.has('ArrowLeft')||keys.has('a'))x=-1;if(keys.has('ArrowRight')||keys.has('d'))x=1;if(keys.has('ArrowUp')||keys.has('w'))y=-1;if(keys.has('ArrowDown')||keys.has('s'))y=1;const length=Math.hypot(x,y);const dt=Math.min(engine.getDeltaTime()/1000,.04);if(length>.08){x/=length;y/=length;direction=Math.abs(x)>Math.abs(y)?(x<0?'left':'right'):(y<0?'up':'down');player.moveWithCollisions(new BABYLON.Vector3(x*(MOVE_SPEED/50)*dt,0,y*(MOVE_SPEED/50)*dt));player.position.x=Math.max(-9.4,Math.min(9.4,player.position.x));player.position.z=Math.max(-35,Math.min(35,player.position.z));}animatePlayer(length>.08,dt);const target=new BABYLON.Vector3(player.position.x,0,player.position.z);camera.target.copyFrom(target);camera.position.x=target.x;camera.position.z=target.z+8;updateZone();}
function updateZone(){if(!player)return;const next=player.position.z<-12?0:player.position.z<12?1:2;if(next!==zoneIndex){zoneIndex=next;document.querySelector('#location').textContent=`✦ ${ZONES[next].name}`;}}
function startTouch(e){origin={x:e.clientX,y:e.clientY};const i=document.querySelector('#touch-indicator');i.style.left=`${e.clientX}px`;i.style.top=`${e.clientY}px`;i.classList.add('active');}
function dragTouch(e){if(!origin)return;const dx=e.clientX-origin.x,dy=e.clientY-origin.y,d=Math.hypot(dx,dy)||1,k=Math.min(38,d);vector={x:dx/d*k/38,y:dy/d*k/38};document.querySelector('#touch-knob').style.transform=`translate(${vector.x*38}px,${vector.y*38}px)`;}
function stopTouch(){origin=null;vector={x:0,y:0};document.querySelector('#touch-indicator').classList.remove('active');document.querySelector('#touch-knob').style.transform='';}
function nearest(){return npcs.find(n=>Math.hypot(n.x-player.position.x,n.z-player.position.z)<2.2);}
function drawPortrait(index){const c=document.querySelector('#portrait'),p=c.getContext('2d'),image=new Image();image.onload=()=>{p.clearRect(0,0,56,56);p.imageSmoothingEnabled=false;p.drawImage(image,96,0,96,128,0,0,56,56);};image.src=`assets/npcs/npc-idle-${index}.png`;}
function interact(){const npc=nearest();if(!npc){document.querySelector('#words').textContent='沿著石板路尋找村民吧。';return;}activeNpc=npc;line=0;talking=true;document.querySelector('#story').className='active';document.querySelector('#story-cg').src=`assets/village-cg-${npc.face}.png`;document.querySelector('#story-name').textContent=npc.name;advanceStory();}
function advanceStory(){if(!activeNpc)return;if(line>=activeNpc.lines.length)return endStory();document.querySelector('#story-text').textContent=activeNpc.lines[line++];}
function endStory(){document.querySelector('#story').className='';document.querySelector('#speaker').textContent=activeNpc.name;document.querySelector('#words').textContent='這段對話已經聽完了。';drawPortrait(activeNpc.face);activeNpc=null;talking=false;}
const keys=new Set();function bindDom(){const canvas=document.querySelector('#game');canvas.addEventListener('pointerdown',startTouch);canvas.addEventListener('pointermove',dragTouch);canvas.addEventListener('pointerup',stopTouch);canvas.addEventListener('pointercancel',stopTouch);document.querySelector('#talk').addEventListener('pointerdown',e=>{e.stopPropagation();interact();});document.querySelector('#story').addEventListener('pointerdown',e=>{e.stopPropagation();advanceStory();});addEventListener('keydown',e=>{keys.add(e.key);if(e.key===' '||e.key==='Enter')interact();});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('resize',()=>{engine.resize();resizeCamera();});}
const canvas=document.querySelector('#game');engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,adaptToDeviceRatio:true});if(innerWidth<600)engine.setHardwareScalingLevel(1.25);bindDom();createScene();engine.runRenderLoop(()=>scene.render());drawPortrait(0);
