from pathlib import Path
import unittest

ROOT = Path(__file__).parents[1]


class VillageAppContract(unittest.TestCase):
    def test_mobile_adventure_has_a_playable_map_and_touch_controls(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")
        css = (ROOT / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="game"', html)
        self.assertIn("pointerdown", js)
        self.assertIn("keydown", js)
        self.assertIn("function move", js)
        self.assertIn("function interact", js)
        self.assertIn("npc", js)
        self.assertIn("image-rendering: pixelated", css)
        self.assertIn("touch-action: none", css)

    def test_mobile_controls_use_a_drag_thumbstick_and_tap_to_talk(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")
        css = (ROOT / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="touch-indicator"', html)
        self.assertIn('id="touch-knob"', html)
        self.assertIn("pointermove", js)
        self.assertIn("addEventListener('pointermove'", js)
        self.assertIn("#touch-indicator", css)
        # No permanent dialogue panel and no talk button — a tap near an NPC opens the conversation.
        self.assertNotIn('id="talk"', html)
        self.assertNotIn('id="dialogue"', html)
        self.assertIn('id="hint"', html)
        self.assertIn('id="debug-toggle"', html)
        self.assertIn('id="camera-reset"', html)
        for control in ["debug-x", "debug-y", "debug-z", "debug-angle", "debug-view"]:
            self.assertIn(f'id="{control}"', html)
        self.assertIn('id="camera-pad"', html)
        self.assertIn("syncDebugCamera", js)
        self.assertIn("debugPointers", js)
        self.assertIn("resetDebugCamera", js)
        self.assertIn("nearest()", js)

    def test_world_is_true_3d_with_billboard_sprites_and_xz_movement(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")

        self.assertIn("vendor/babylon.js", html)
        self.assertNotIn("vendor/phaser.min.js", html)
        self.assertIn("new BABYLON.Engine", js)
        self.assertIn("new BABYLON.Scene", js)
        self.assertIn("MeshBuilder.CreateGround", js)
        self.assertIn("MeshBuilder.CreatePlane", js)
        self.assertIn("BILLBOARDMODE_Y", js)
        self.assertIn("moveWithCollisions", js)
        self.assertIn("camera.setTarget(new BABYLON.Vector3(targetX, targetY, CAM.targetZ))", js)
        self.assertIn("const ZONES", js)
        self.assertIn("function createBuilding", js)
        self.assertIn("BUILDING_ASPECT", js)
        self.assertIn("const fittedWidth = height * BUILDING_ASPECT[key]", js)
        self.assertIn("FOREGROUND_ASPECT", js)
        self.assertIn("assets/foreground/", js)
        self.assertIn("createForegroundAsset", js)

    def test_iphone_uses_fullscreen_map_and_anywhere_touch_joystick(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")
        css = (ROOT / "style.css").read_text(encoding="utf-8")

        self.assertNotIn('id="joystick"', html)
        self.assertIn('id="touch-indicator"', html)
        self.assertIn("addEventListener('pointerdown'", js)
        self.assertIn("pointercancel", js)
        self.assertIn("engine.setSize(LANDSCAPE_RENDER.width, LANDSCAPE_RENDER.height)", js)
        self.assertIn("100dvh", css)
        self.assertIn("position:fixed", css.replace(" ", ""))
        self.assertIn("inset:0", css.replace(" ", ""))

    def test_character_is_large_and_touch_movement_is_responsive(self):
        js = (ROOT / "game.js").read_text(encoding="utf-8")

        self.assertIn("const MOVE_SPEED=280", js)
        self.assertIn("const CHARACTER_SCALE=1.75", js)
        self.assertIn("hero-walk.png", js)
        self.assertIn("setSpriteFrame", js)
        self.assertIn("animatePlayer", js)
        self.assertIn("{down:3,left:2,right:1,up:3}", js)
        self.assertIn("moveWithCollisions", js)

    def test_game_uses_local_babylon_engine_with_3d_camera_lighting_and_postprocess(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")
        css = (ROOT / "style.css").read_text(encoding="utf-8")

        self.assertIn('vendor/babylon.js', html)
        self.assertIn("new BABYLON.Engine", js)
        self.assertIn("new BABYLON.Scene", js)
        self.assertIn("new BABYLON.HemisphericLight", js)
        self.assertIn("new BABYLON.DirectionalLight", js)
        self.assertIn("new BABYLON.ShadowGenerator", js)
        self.assertIn("new BABYLON.DefaultRenderingPipeline", js)
        self.assertIn("pipeline.depthOfFieldEnabled = false", js)
        self.assertIn("pipeline.fxaaEnabled = false", js)
        self.assertIn("bloomEnabled", js)
        self.assertIn("function loadAssets", js)
        self.assertIn("assets/buildings/${key}.png", js)
        self.assertIn("'guild','magic','alchemy','smithy','tavern'", js)
        self.assertIn("new BABYLON.StandardMaterial", js)
        self.assertIn("npc-idle-${i}.png", js)
        self.assertIn("function createGround", js)
        self.assertIn("function createTown", js)
        self.assertIn("BABYLON.Camera.ORTHOGRAPHIC_CAMERA", js)
        self.assertIn("view: 5.0", js)
        self.assertIn("height: 8.0, back: 21", js)
        self.assertNotIn("WIDE_ANGLE", js)
        self.assertIn("camera.orthoLeft = -view * aspect", js)
        self.assertIn("0, 0.8, 2.0, 2.75", js)
        self.assertIn("const targetVisibility = near ? .15 : 1", js)
        self.assertIn("createEnvironmentEffects", js)
        self.assertIn("pipeline.imageProcessing.vignetteEnabled", js)
        self.assertIn("new BABYLON.PBRMaterial", js)
        self.assertIn("useParallaxOcclusion", js)
        self.assertIn("groundMaterial('ground', 200, 26)", js)
        self.assertIn("TONEMAPPING_ACES", js)
        self.assertIn("createSunsetSky", js)
        self.assertIn("sunset-cloud", js)
        self.assertIn("sunbeam", js)
        self.assertIn("dust-motes", js)
        self.assertIn("BABYLON.Effect.ShadersStore['volumetricLightFragmentShader']", js)
        self.assertIn("new BABYLON.PostProcess('volumetric-light'", js)
        self.assertIn("new BABYLON.Layer('visible-sunshafts'", js)
        self.assertIn("drawVisibleSunshafts", js)
        self.assertIn("ps.emitRate = 34", js)
        self.assertIn("createFacadeSpotlights", js)
        self.assertIn("new BABYLON.SpotLight", js)
        self.assertIn("facadeSpot.specular", js)
        self.assertIn("registerStreamedVisual", js)
        self.assertIn("updateAssetStreaming", js)
        self.assertIn("STREAM_DISTANCE", js)
        self.assertIn("STREAM_RELEASE_DISTANCE = 32", js)
        self.assertIn("streamedMaterialCache", js)
        self.assertIn("MOBILE_RENDER", js)
        self.assertIn("FRAME_INTERVAL = 1000 / 60", js)
        self.assertIn("clouds.position.set(0, 7.8, -17.5)", js)
        self.assertIn("new BABYLON.Vector3(.28, -.9, -.72)", js)
        self.assertIn("LANDSCAPE_RENDER = { width: 2796, height: 1290 }", js)
        self.assertIn("engine.setSize(LANDSCAPE_RENDER.width, LANDSCAPE_RENDER.height)", js)
        self.assertIn("RENDER_DISTANCE", js)
        self.assertIn("ground-ray", js)
        self.assertIn("user-select:none", css.replace(" ", ""))
        for texture in ["medieval_cobble_color.jpg", "medieval_cobble_normal.jpg", "medieval_cobble_roughness.jpg", "medieval_cobble_ao.jpg"]:
            self.assertTrue((ROOT / f"assets/textures/{texture}").exists(), texture)
            self.assertIn(texture, js)
        self.assertIn("backdrop-filter:blur", css)
        self.assertIn("radial-gradient", css)
        self.assertIn("mix-blend-mode", css)
        self.assertIn("[-31,-26,-21,-16,-7,-2,3,8,15,20,25,30]", js)
        fantasy_buildings = ["guild", "magic", "alchemy", "smithy", "tavern", "bakery", "flower", "chapel", "home", "clocktower", "market"]
        for key in fantasy_buildings:
            self.assertTrue((ROOT / f"assets/buildings/{key}.png").exists(), key)
            self.assertIn(f"'{key}'", js)
        self.assertIn("npc-idle-${i}.png", js)
        self.assertTrue((ROOT / "assets/village-cg-5.png").exists())
        self.assertIn("name:'艾妲'", js)
        self.assertIn("name:'凱恩'", js)
        self.assertIn("name:'菲菲'", js)
        self.assertEqual(js.count(",face:"), 6)
        for index in range(6):
            self.assertTrue((ROOT / f"assets/npcs/npc-idle-{index}.png").exists())
            self.assertTrue((ROOT / f"assets/village-cg-{index}.png").exists())

    def test_foreground_houses_sit_low_in_the_portrait_frame(self):
        js = (ROOT / "game.js").read_text(encoding="utf-8")

        self.assertIn("p.position.set(x, height / 2, z)", js)
        self.assertIn("const foregroundProps = [", js)
        self.assertIn("step:12.4, count:6", js)
        self.assertIn("step:12.8, count:6", js)
        self.assertIn("const backgroundCottages =", js)
        self.assertIn("createForegroundAsset(key, x, height, i % 2 === 0, -8.2, false)", js)
        self.assertNotIn("source:'building'", js)
        self.assertIn("height: 164", js)
        self.assertIn("g.position.z = 64", js)
        self.assertIn("'merchant-wagon'", js)
        self.assertIn("'flower-well'", js)
        for foreground_type in ["red-bakery", "blue-smithy", "moss-workshop", "fishing-shack", "red-cottage", "stable", "purple-potion", "honey-lodge", "moon-cottage", "boathouse", "moss-shrine", "greenhouse"]:
            self.assertIn(f"'{foreground_type}'", js)

    def test_dialogue_opens_fullscreen_character_cg_and_completes_story(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "game.js").read_text(encoding="utf-8")
        css = (ROOT / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="story"', html)
        self.assertIn('id="story-cg"', html)
        self.assertIn('id="story-text"', html)
        self.assertIn("function advanceStory", js)
        self.assertIn("endStory", js)
        self.assertIn("village-cg-0.png", html)
        self.assertIn("village-cg-${npc.face}.png", js)
        self.assertIn("#story.active", css)


if __name__ == "__main__":
    unittest.main()
